name: Claude PR Assistant

on:
  workflow_call:
    secrets:
      ANTHROPIC_API_KEY:
        description: 'Anthropic API key for Claude'
        required: true

jobs:
  claude-code-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Claude PR Action
        uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          allowed_tools: "Bash(gh:*),Read,View"
          timeout_minutes: "5"
          direct_prompt: |
            You are a helpful AI assistant for GitHub Pull Requests.
            
            If this was triggered by a PR comment with @claude_pr:
            - Read the comment content and understand what the user is asking
            - Analyze the PR changes in the context of the user's request
            - Provide a helpful response by updating the PR description or adding a comment
            
            If this was triggered by a new PR being opened:
            - Analyze the changes in this PR
            - Format them according to .github/PULL_REQUEST_TEMPLATE.md if it exists
            - Update the PR description using gh pr edit
            
            Always be helpful and provide clear, actionable feedback.
