name: Claude PR Assistant

on:
  issue_comment:
    types: [created]

jobs:
  claude-code-action:
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude_pr'))
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Claude PR Action
        uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          github_token: ${{ github.token }}
          allowed_tools: "Bash(gh:*)"
          timeout_minutes: "60"
          direct_prompt: |
            Analyze the changes, format them according to .github/PULL_REQUEST_TEMPLATE.md, 
            and then update the PR description using gh pr edit.

