name: Claude PR Assistant

on:
  issue_comment:
    types: [created]

jobs:
  claude-code-action:
    if: |
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '@claude_pr'))
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      issues: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Claude PR Action
        id: claude
        uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          github_token: ${{ github.token }}
          allowed_tools: "Read,View,Bash(echo *)"
          timeout_minutes: "60"
          direct_prompt: |
            Analyze the changes in this PR and format them according to .github/PULL_REQUEST_TEMPLATE.md.
            
            At the end, save your PR description to a file using:
            echo "YOUR_PR_DESCRIPTION_HERE" > /tmp/pr_description.md
            
            Make sure to replace YOUR_PR_DESCRIPTION_HERE with the actual formatted description.

      - name: Update PR with Claude's analysis
        if: ${{ github.event.issue.pull_request }}
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          PR_NUMBER=${{ github.event.issue.number }}
          
          # Claude가 생성한 파일 확인
          if [ -f /tmp/pr_description.md ]; then
            gh pr edit $PR_NUMBER --body-file /tmp/pr_description.md
            echo "✅ PR description updated successfully"
          else
            echo "❌ PR description file not found"
            exit 1
          fi

