name: Claude PR Assistant

on:
  workflow_call:
    secrets:
      ANTHROPIC_API_KEY:
        description: 'Anthropic API key for Claude'
        required: true

jobs:
  claude-code-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Run Claude PR Action
        uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          allowed_tools: Bash(gh:*),Read,View
          timeout_minutes: 10
          direct_prompt: |
            You are a PR description formatter. Your ONLY task is to format the PR description according to the template.

            Instructions:
            1. Gather information about this PR:
               - Check what files were changed (use git diff, gh pr view, or other methods)
               - Understand the scope and nature of the changes
               - Get the current PR title and description if any
            2. Check if `.github/PULL_REQUEST_TEMPLATE.md` exists by reading the file
            3. If template exists:
               - Fill in each section of the template with relevant information from the PR changes
               - Replace placeholder text (e.g., "Brief description of changes") with actual content
               - Keep the template structure exactly as is
            4. If no template exists:
               - Create a clean markdown description with: Title, Description, Changes, and Files Modified
            5. Create pr formatted description to /tmp/pr_description.md and update PR description using the formatted file

            Important rules:
            - Do NOT add code review comments or suggestions
            - Do NOT analyze code quality or performance
            - ONLY focus on filling out the description template accurately
            - Keep descriptions concise and factual
            - Preserve any existing template formatting (checkboxes, headers, etc.)